version: '3.8'

name: blockchain-arduino

services:
  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache
    ports:
      - "8545:8545"
    networks:
      - backend
    volumes:
      - ./ganache-data:/root/.ganache

  ipfs:
    image: ipfs/go-ipfs
    container_name: ipfs
    volumes:
      - ./ipfs-data:/data/ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    networks:
      - backend
    environment:
      - IPFS_API_URL=http://ipfs:5001  # Correct URL to access IPFS API internally
    restart: unless-stopped

#  hardhat:
#    image: node:18
#    container_name: hardhat
#    working_dir: /app
#    volumes:
#      - ./blockchain:/app
#    entrypoint: /bin/sh
#    networks:
#      - backend

  python-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-server
    depends_on:
      - ganache
      - ipfs
    ports:
      - "5002:5002"
    networks:
      - backend
    environment:
      - IPFS_API_URL=http://ipfs:5001
      - GANACHE_URL=http://ganache:8545

networks:
  backend:
    name: backend  # Forces the name to "backend"
    driver: bridge

volumes:
  ipfs-data:
  ganache-data:
