# Use Node.js as the base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

COPY hardhat.config.js ./
COPY contracts/ ./contracts
COPY scripts/ ./scripts

# Expose Hardhat's default port
EXPOSE 7545

# Start Hardhat
CMD ["npx", "hardhat", "node", "--hostname", "0.0.0.0"]
