version: '3.8'

name: blockchain-arduino

services:
  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache
    ports:
      - "8545:8545"
    networks:
      - backend
    volumes:
      - ./ganache-data:/root/.ganache

  ipfs:
    image: ipfs/go-ipfs
    container_name: ipfs
    volumes:
      - ./ipfs-data:/data/ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    networks:
      - backend
    environment:
      - IPFS_API_URL=http://ipfs:5001
    restart: unless-stopped

  hardhat:
    build:
      context: .
      dockerfile: Dockerfile.hardhat
    ports:
      - "7545:7545"
    networks:
      - backend

  python-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-server
    depends_on:
      - ganache
      - ipfs
    ports:
      - "5002:5002"
      - "8000:8000"
    networks:
      - backend
    environment:
      - IPFS_API_URL=http://ipfs:5001
      - GANACHE_URL=http://ganache:8545
      - HARDHAT_URL=http://hardhat:7545
    privileged: true  # Grant extra privileges to access hardware
    volumes:
      - "/dev/ttyS4:/dev/ttyS4"
    devices:
      - "/dev/ttyS4:/dev/ttyS4"  # Bluetooth device path


networks:
  backend:
    name: backend  # Forces the name to "backend"
    driver: bridge

volumes:
  ipfs-data:
  ganache-data:
